CREATE TABLE IF NOT EXISTS person
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    created_at DATE,
    removed BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS task
(
    id          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    start_date  DATE,
    end_date    DATE,
    description VARCHAR(500),
    removed  BOOLEAN DEFAULT FALSE,
    user_id     BIGINT,
    FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS file
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    file_name  VARCHAR(255) NOT NULL,
    removed BOOLEAN DEFAULT FALSE,
    task_id    BIGINT,
    FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tag
(
    id   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE task_tag
(
    task_id BIGINT NOT NULL REFERENCES task (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tag (id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, tag_id)
);